
title: Artist Portfolio Website - Zaida Guerrero Casado
description: showcasing projects of the artist
url: "http://zaidaguerrerocasado.com/"

# erstellt von:
github_username: fraenze-st


# Build settings
markdown: kramdown


sass:
    sass_dir: /assets/scss/
    style: :nested

collections:
  posts:
    permalink: /:title/

